version: '3.3'

services:
  db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb_read_only_compressed=OFF
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1
    networks:
      - nextcloud

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    networks:
        - nextcloud
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}

  app:
    image: nextcloud-plus
    build:
      context: ./docker
      args:
        baseImage: nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
        REDIS_HOST: nextcloud-redis
        REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: nextcloud
        MYSQL_HOST: nextcloud-db
    volumes:
      - ./data/app:/var/www/html
      - ./data/data:/var/www/html/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-app.entrypoints=web"
#      - "traefik.http.routers.nextcloud-app.rule=Host(`cloud.ditscher.me`, `cloud.ditschers.de`, `newcloud.ditschers.de`, `cloud.vps.ditscher.me`, `cloud.vps.ditschers.de`, `newcloud.vps.ditschers.de`)"
      - "traefik.http.routers.nextcloud-app.rule=Host(`cloud.ditschers.de`, `newcloud.ditschers.de`, `cloud.vps.ditschers.de`, `newcloud.vps.ditschers.de`)"
      - "traefik.http.routers.nextcloud-app.middlewares=https-redirect@file"
      - "traefik.http.routers.nextcloud-app-secure.entrypoints=websecure"
#      - "traefik.http.routers.nextcloud-app-secure.rule=Host(`cloud.ditscher.me`, `cloud.ditschers.de`, `newcloud.ditschers.de`, `cloud.vps.ditscher.me`, `cloud.vps.ditschers.de`, `newcloud.vps.ditschers.de`)"
      - "traefik.http.routers.nextcloud-app-secure.rule=Host(`cloud.ditschers.de`, `newcloud.ditschers.de`, `cloud.vps.ditschers.de`, `newcloud.vps.ditschers.de`)"
      - "traefik.http.routers.nextcloud-app-secure.tls=true"
      - "traefik.http.routers.nextcloud-app-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud-app-secure.service=nextcloud-app"
      - "traefik.http.services.nextcloud-app.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nextcloud-app-secure.middlewares=nextcloud-dav,secHeaders@file"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"
    networks:
      - traefik
      - nextcloud

networks:
  nextcloud:
  traefik:
    external: true
